export default {
  genres: [
    { name: "Action" },
    { name: "Adventure" },
    { name: "Animation" },
    { name: "Comedy" },
    { name: "Drama" },
    { name: "Family" },
    { name: "Fantasy" },
    { name: "Horror" },
    { name: "Music" },
    { name: "Mystery" },
    { name: "Romance" },
    { name: "Sci-Fi" },
    { name: "Thriller" },
    { name: "War" }
  ],
  movies: [
// {
//   "trailer": "",
//   "torrent": "",
//   "es": "",
//   "en": "",
//   "fr": "",
//   "br": "",
//   "ita": ""
// }
    // {
    //   "genres": "Drama Romance"
    //   "adult": false,
    //   "backdrop_path": "/kU5qE5b6ksL3osaqKCUlMS08Ays.jpg",
    //   "belongs_to_collection": null,
    //   "budget": 0,
    //   "homepage": "https://www.thephotographmovie.com/",
    //   "id": 589049,
    //   "imdb_id": "tt7798646",
    //   "original_language": "en",
    //   "original_title": "The Photograph",
    //   "overview": "When famed photographer Christina Eames dies unexpectedly, she leaves her estranged daughter, Mae, hurt, angry and full of questions. When Mae finds a photograph tucked away in a safe-deposit box, she soon finds herself delving into her mother's early life -- an investigation that leads to an unexpected romance with a rising journalist.",
    //   "popularity": 34.821,
    //   "poster_path": "/cdqZqIcWt0Ne2Io2OA9iWqqMuCA.jpg",
    //   "release_date": "2020-02-14",
    //   "revenue": 0,
    //   "runtime": 106,
    //   "status": "Released",
    //   "tagline": "",
    //   "title": "The Photograph",
    //   "video": false,
    //   "vote_average": 7.4,
    //   "vote_count": 25,
    //   "trailer": "kmicB3J1emw",
    //   "torrent": "AA87BE94B74B9CA4172939E7F1045D2E50DD1C56",
    //   "es": "",
    //   "en": "",
    //   "fr": "",
    //   "br": "",
    //   "ita": ""
    // },
    {
      "genres": "Drama Action Thriller",
      "adult": false,
      "backdrop_path": "/1R6cvRtZgsYCkh8UFuWFN33xBP4.jpg",
      "belongs_to_collection": null,
      "budget": 0,
      "homepage": "https://www.netflix.com/title/80230399",
      "id": 545609,
      "imdb_id": "tt8936646",
      "original_language": "en",
      "original_title": "Extraction",
      "overview": "Tyler Rake, a fearless mercenary who offers his services on the black market, embarks on a dangerous mission when he is hired to rescue the kidnapped son of a Mumbai crime lord…",
      "popularity": 479.497,
      "poster_path": "/wlfDxbGEsW58vGhFljKkcR5IxDj.jpg",
      "release_date": 2020,
      "revenue": 0,
      "runtime": 116,
      "status": "Released",
      "tagline": "When the mission ends, redemption begins",
      "title": "Extraction",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 1210,
      "trailer": "L6P3nI6VnlY",
      "torrent": "5EB5104B94724F2AEF5D1D3545DE45833E8FE614",
      "es": "https://www.seedr.cc/subtitles/1956753920/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19de0c58%2Fsid-gjWAYiRJhSJ0xbd1mYszmmLS6wb%2Ffilead%2F1956753920.gz/sub.vtt",
      "en": "https://www.seedr.cc/subtitles/1956751627/eng/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d40c5a%2Fsid-lyxRD9OEsorFzlZpNMvlzO1Sgwa%2Ffilead%2F1956751627.gz/sub.vtt",
      "fr": "https://www.seedr.cc/subtitles/1956752300/fre/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19c40c4f%2Fsid-M-BzC4tVXQMFKEAkUFo8fRwFFy6%2Ffilead%2F1956752300.gz/sub.vtt",
      "br": "https://www.seedr.cc/subtitles/1956752167/pob/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d10c5a%2Fsid-suwChu6wfeGJ0GzN2lwxmET5ge9%2Ffilead%2F1956752167.gz/sub.vtt",
      "ita": "https://www.seedr.cc/subtitles/1956751688/ita/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19e10c61%2Fsid-xk7pt-neKIX8q8UYWCFcRphQWva%2Ffilead%2F1956751688.gz/sub.vtt"
    },
    {
      "genres": "Adventure Animation Comedy Family Fantasy",
      "adult": false,
      "backdrop_path": "/m67smI1IIMmYzCl9axvKNULVKLr.jpg",
      "budget": 175000000,
      "homepage": "https://www.pixar.com/feature-films-toy-story-4",
      "id": 301528,
      "imdb_id": "tt1979376",
      "original_language": "en",
      "original_title": "Toy Story 4",
      "overview": "Woody has always been confident about his place in the world and that his priority is taking care of his kid, whether that's Andy or Bonnie. But when Bonnie adds a reluctant new toy called \"Forky\" to her room, a road trip adventure alongside old and new friends will show Woody how big the world can be for a toy.",
      "popularity": 45.403,
      "poster_path": "/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
      "release_date": 2019,
      "revenue": 1073394593,
      "runtime": 100,
      "status": "Released",
      "tagline": "Get Ready to Hit the Road",
      "title": "Toy Story 4",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 4749,
      "trailer": "LDXYRzerjzU",
      "torrent": "0B9C7DD6E98FBB2965706D3719D846C0F2E1367A",
      "es": "https://www.seedr.cc/subtitles/1956465302/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19c50c52%2Fsid-sb8brRqb%2Cu--oWZSAPKw1rd-jc7%2Ffilead%2F1956465302.gz/sub.vtt",
      "en": "https://www.seedr.cc/subtitles/1956464526/eng/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19cf0c59%2Fsid-v7koOSrAPJ7uqxQjwF-QlkrkMu6%2Ffilead%2F1956464526.gz/sub.vtt",
      "fr": "https://www.seedr.cc/subtitles/1956475373/fre/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d90c5b%2Fsid-ngpxlx6jJZF34d8rlD1RtwPk0w4%2Ffilead%2F1956475373.gz/sub.vtt",
      "br": "https://www.seedr.cc/subtitles/1956481755/pob/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d80c5c%2Fsid-MYGoTq3sIqYjWNHilH-mfTFsPEa%2Ffilead%2F1956481755.gz/sub.vtt",
      "ita": "https://www.seedr.cc/subtitles/1956525092/ita/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19c00c55%2Fsid-OTMLk6ayN2aIglGLQuoW1xSGK3b%2Ffilead%2F1956525092.gz/sub.vtt"
    },
    {
      "adult": false,
      "backdrop_path": "/27ZkYMWynuK2qiDP6awc3MsCaOs.jpg",
      "belongs_to_collection": null,
      "budget": 5000000,
      "genres": "Romance Drama",
      "homepage": "https://www.fivefeetapartfilm.com",
      "id": 527641,
      "imdb_id": "tt6472976",
      "original_language": "en",
      "original_title": "Five Feet Apart",
      "overview": "Seventeen-year-old Stella spends most of her time in the hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control — all of which get put to the test when she meets Will, an impossibly charming teen who has the same illness. There's an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction.",
      "popularity": 31.711,
      "poster_path": "/kreTuJBkUjVWePRfhHZuYfhNE1T.jpg",
      "release_date": 2019,
      "revenue": 0,
      "runtime": 116,
      "status": "Released",
      "tagline": "When Life Keeps You Apart, Fight For Every Inch.",
      "title": "Five Feet Apart",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 2450,
      "trailer": "Kwg07npuJhw",
      "torrent": "DBE74C2EF8C14780C622C5C2CF932FC34AA00228",
      "es": "https://www.seedr.cc/subtitles/1956376131/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19c70c53%2Fsid-XSRQOckwhiUfU1CKM28seXqWthb%2Ffilead%2F1956376131.gz/sub.vtt",
      "en": "https://www.seedr.cc/subtitles/1956349814/eng/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d80c5b%2Fsid-bBZ4VJ-EO0v9zV0p9LZocYe4AE7%2Ffilead%2F1956349814.gz/sub.vtt",
      "fr": "https://www.seedr.cc/subtitles/1956406561/fre/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19bc0c54%2Fsid-lqxfIF7WbUN8BFk22qODgYMmnb0%2Ffilead%2F1956406561.gz/sub.vtt",
      "br": "https://www.seedr.cc/subtitles/1956367535/pob/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d60c5b%2Fsid-Wgnq0ljOCmH6eXTB9PAzy2qFab9%2Ffilead%2F1956367535.gz/sub.vtt",
      "ita": "https://www.seedr.cc/subtitles/1956755394/ita/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19e60c5f%2Fsid-bsrX99txiFEv8aTl0k6l6CwUEne%2Ffilead%2F1956755394.gz/sub.vtt"
    },
    {
      "adult": false,
      "backdrop_path": "/2WgieNR1tGHlpJUsolbVzbUbE1O.jpg",
      "belongs_to_collection": null,
      "budget": 100000000,
      "genres": "War Drama Action Thriller",
      "homepage": "https://www.1917.movie/",
      "id": 530915,
      "imdb_id": "tt8579674",
      "original_language": "en",
      "original_title": "1917",
      "overview": "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
      "popularity": 88.742,
      "poster_path": "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
      "release_date": 2019,
      "revenue": 368027644,
      "runtime": 119,
      "status": "Released",
      "tagline": "Time is the enemy",
      "title": "1917",
      "video": false,
      "vote_average": 8,
      "vote_count": 4605,
      "trailer": "UcmZN0Mbl04",
      "torrent": "BCA973373EBDE35C3887D026C7929B8017A3572B",
      "es": "https://www.seedr.cc/subtitles/1956704174/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19bf0c55%2Fsid-RkxAQNCD1qticLcLXojPb%2CMthDd%2Ffilead%2F1956704174.gz/sub.vtt",
      "en": "https://www.seedr.cc/subtitles/1956630349/eng/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19bd0c57%2Fsid-GrruLoJ5aU%2CH8sAq%2CiRQZwz4yE6%2Ffilead%2F1956630349.gz/sub.vtt",
      "fr": "https://www.seedr.cc/subtitles/1956644801/fre/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d10c55%2Fsid-VlUHpa7p8hdfxXZhcQLJIZ7-NF9%2Ffilead%2F1956644801.gz/sub.vtt",
      "br": "https://www.seedr.cc/subtitles/1956690982/pob/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19ee0c60%2Fsid-mM5BHULaBpIAb5DJCWq5CvWKLd2%2Ffilead%2F1956690982.gz/sub.vtt",
      "ita": "https://www.seedr.cc/subtitles/1956693384/ita/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19ea0c5f%2Fsid-jh9DorzD2QM3GCoqljO3rGM79Ie%2Ffilead%2F1956693384.gz/sub.vtt"
    },
    {
      "adult": false,
      "backdrop_path": "/8wGpjCDAlwpOm1F1onhkhJq16lY.jpg",
      "budget": 160000000,
      "genres": "Action Adventure Sci-Fi",
      "homepage": "http://www.thehungergames.movie/",
      "id": 131634,
      "imdb_id": "tt1951266",
      "original_language": "en",
      "original_title": "The Hunger Games: Mockingjay - Part 2",
      "overview": "With the nation of Panem in a full scale war, Katniss confronts President Snow in the final showdown. Teamed with a group of her closest friends – including Gale, Finnick, and Peeta – Katniss goes off on a mission with the unit from District 13 as they risk their lives to stage an assassination attempt on President Snow who has become increasingly obsessed with destroying her. The mortal traps, enemies, and moral choices that await Katniss will challenge her more than any arena she faced in The Hunger Games.",
      "popularity": 29.594,
      "poster_path": "/lImKHDfExAulp16grYm8zD5eONE.jpg",
      "release_date": 2015,
      "revenue": 653428261,
      "runtime": 137,
      "status": "Released",
      "tagline": "The fire will burn forever.",
      "title": "The Hunger Games: Mockingjay - Part 2",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 8615,
      "trailer": "n-7K_OjsDCQ",
      "torrent": "42FDF1AEEE3C641BE8C41BC1FEEDDF87A50CAE12",
      "es": "https://www.seedr.cc/subtitles/1955172160/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19a90c4e%2Fsid-V32pM-kSxqYRFpDjtU6Sgf7X2L1%2Ffilead%2F1955172160.gz/sub.vtt",
      "en": "https://www.seedr.cc/subtitles/1954631756/eng/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19be0c58%2Fsid-rM5AId7TxBsvI5kXJoc0sXBHZad%2Ffilead%2F1954631756.gz/sub.vtt",
      "fr": "https://www.seedr.cc/subtitles/1954781216/fre/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19c60c55%2Fsid-VYC0MCMvPN55ufetI3KJOmtGpT7%2Ffilead%2F1954781216.gz/sub.vtt",
      "br": "https://www.seedr.cc/subtitles/1955123694/pob/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19ad0c56%2Fsid-WX-q3JloQtkAHcfUlYKaT%2CsgWU7%2Ffilead%2F1955123694.gz/sub.vtt",
      "ita": "https://www.seedr.cc/subtitles/1955139996/ita/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19d50c62%2Fsid-SqQE8-KNfTSnp47Kkk0992wXHY5%2Ffilead%2F1955139996.gz/sub.vtt"
    },
    {
      "adult": false,
      "backdrop_path": "/stemLQMLDrlpfIlZ5OjllOPT8QX.jpg",
      "budget": 55000000,
      "genres": "Action Thriller Crime",
      "homepage": "https://www.johnwick.movie",
      "id": 458156,
      "imdb_id": "tt6146586",
      "original_language": "en",
      "original_title": "John Wick: Chapter 3 - Parabellum",
      "overview": "Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
      "popularity": 49.58,
      "poster_path": "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
      "release_date": 2019,
      "revenue": 326699296,
      "runtime": 131,
      "status": "Released",
      "tagline": "The Grace Period Is Over",
      "title": "John Wick: Chapter 3 - Parabellum",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 4734,
      "trailer": "M7XM597XO94",
      "torrent": "43D8135EB4EA2036FF1D22D4DCEDED5587A953E0",
      "es": "https://yify-api.now.sh/subs/tt6146586/91",
      "en": "https://yify-api.now.sh/subs/tt6146586/28",
      "fr": "https://yify-api.now.sh/subs/tt6146586/70",
      "br": "https://yify-api.now.sh/subs/tt6146586/10",
      "ita": "https://yify-api.now.sh/subs/tt6146586/0"
    },
    {
      "genres": "Action Sci-Fi",
      "adult": false,
      "backdrop_path": "/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg",
      "belongs_to_collection": null,
      "budget": 42000000,
      "homepage": "https://www.bloodshot.movie/",
      "id": 338762,
      "imdb_id": "tt1634106",
      "original_language": "en",
      "original_title": "Bloodshot",
      "overview": "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
      "popularity": 246.229,
      "poster_path": "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
      "release_date": 2020,
      "revenue": 24573617,
      "runtime": 110,
      "status": "Released",
      "tagline": "Being a superhero is in his blood",
      "title": "Bloodshot",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2014,
      "trailer": "QvwsqGd4mh8",
      "torrent": "5CE0BFBA1C5A73CED27E47D5E24BAAB162B5C97E",
      "es": "https://yify-api.now.sh/subs/tt1634106/49",
      "en": "https://yify-api.now.sh/subs/tt1634106/14",
      "fr": "https://yify-api.now.sh/subs/tt1634106/35",
      "br": "https://yify-api.now.sh/subs/tt1634106/6",
      "ita": "https://yify-api.now.sh/subs/tt1634106/0"
    },
    {
      "adult": false,
      "backdrop_path": "/rYsdoUqkltpKZQWwCWXf55csXvL.jpg",
      "budget": 125000000,
      "genres": "Sci-Fi Adventure Thriller",
      "homepage": "http://www.thehungergames.movie/",
      "id": 131631,
      "imdb_id": "tt1951265",
      "original_language": "en",
      "original_title": "The Hunger Games: Mockingjay - Part 1",
      "overview": "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
      "popularity": 49.034,
      "poster_path": "/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
      "release_date": 2014,
      "revenue": 752100229,
      "runtime": 123,
      "status": "Released",
      "tagline": "Fire burns brighter in the darkness",
      "title": "The Hunger Games: Mockingjay - Part 1",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 11359,
      "trailer": "C_Tsj_wTJkQ",
      "torrent": "C353F618210665A77BCE482A1EE571112E24AFC3",
      "es": "https://yify-api.now.sh/subs/tt1951265/78",
      "en": "https://yify-api.now.sh/subs/tt1951265/15",
      "fr": "https://yify-api.now.sh/subs/tt1951265/42",
      "br": "https://yify-api.now.sh/subs/tt1951265/3",
      "ita": "https://yify-api.now.sh/subs/tt1951265/1"
    },
    {
      "adult": false,
      "backdrop_path": "/997ToEZvF2Obp9zNZbY5ELVnmrW.jpg",
      "belongs_to_collection": null,
      "budget": 14000000,
      "genres": "Drama Romance",
      "homepage": "",
      "id": 537915,
      "imdb_id": "tt4126476",
      "original_language": "en",
      "original_title": "After",
      "overview": "Tessa Young is a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart. Entering her first semester of college, Tessa's guarded world opens up when she meets Hardin Scott, a mysterious and brooding rebel who makes her question all she thought she knew about herself -- and what she wants out of life.",
      "popularity": 33.64,
      "poster_path": "/u3B2YKUjWABcxXZ6Nm9h10hLUbh.jpg",
      "release_date": 2019,
      "revenue": 69497587,
      "runtime": 106,
      "status": "Released",
      "tagline": "After your first, life is never the same.",
      "title": "After",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 3216,
      "trailer": "2ZAdcWHuCmY",
      "torrent": "CE58C3D4917225559C5E3B2F1C208054D294A204",
      "es": "https://yify-api.now.sh/subs/tt4126476/41",
      "en": "https://yify-api.now.sh/subs/tt4126476/10",
      "fr": "https://yify-api.now.sh/subs/tt4126476/",
      "br": "https://yify-api.now.sh/subs/tt4126476/",
      "ita": "https://yify-api.now.sh/subs/tt4126476/0"
    },
    {
      "adult": false,
      "backdrop_path": "/2duvg8bPkSKq5pekqzBgwyCYAxI.jpg",
      "belongs_to_collection": null,
      "budget": 13000000,
      "genres": "Comedy Drama Fantasy",
      "homepage": "",
      "id": 492,
      "imdb_id": "tt0120601",
      "original_language": "en",
      "original_title": "Being John Malkovich",
      "overview": "One day at work, unsuccessful puppeteer Craig finds a portal into the head of actor John Malkovich. The portal soon becomes a passion for anybody who enters its mad and controlling world of overtaking another human body.",
      "popularity": 18.103,
      "poster_path": "/oS3zTDxqHtyKDidHHvG66P7Mcg.jpg",
      "release_date": 1999,
      "revenue": 22863596,
      "runtime": 113,
      "status": "Released",
      "tagline": "Ever wanted to be someone else? Now you can.",
      "title": "Being John Malkovich",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 2543,
      "trailer": "XXFc3GY1u2g",
      "torrent": "34D10E662F872B4E4858439D9A336B930032162B",
      "es": "https://yify-api.now.sh/subs/tt0120601/22",
      "en": "https://yify-api.now.sh/subs/tt0120601/11",
      "fr": "https://yify-api.now.sh/subs/tt0120601/17",
      "br": "https://yify-api.now.sh/subs/tt0120601/2",
      "ita": "https://yify-api.now.sh/subs/tt0120601/0"
    },
    {
      "adult": false,
      "backdrop_path": "/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg",
      "budget": 200000000,
      "genres": "Action Adventure Animation Family",
      "homepage": "https://movies.disney.com/incredibles-2",
      "id": 260513,
      "imdb_id": "tt3606756",
      "original_language": "en",
      "original_title": "Incredibles 2",
      "overview": "Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.",
      "popularity": 30.682,
      "poster_path": "/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg",
      "release_date": 2018,
      "revenue": 1241891456,
      "runtime": 118,
      "status": "Released",
      "tagline": "Back to work.",
      "title": "Incredibles 2",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 8233,
      "trailer": "i5qOzqD9Rms",
      "torrent": "6B7469C830B624321F843A95D0BD162AAF2ABFF4",
      "es": "https://yify-api.now.sh/subs/tt3606756/37",
      "en": "https://yify-api.now.sh/subs/tt3606756/10",
      "fr": "https://yify-api.now.sh/subs/tt3606756/26",
      "br": "https://yify-api.now.sh/subs/tt3606756/3",
      "ita": "https://yify-api.now.sh/subs/tt3606756/0"
    },
    {
      "adult": false,
      "backdrop_path": "/9ywA15OAiwjSTvg3cBs9B7kOCBF.jpg",
      "budget": 55000000,
      "genres": "Drama Romance",
      "homepage": "http://www.fiftyshadesmovie.com",
      "id": 337167,
      "imdb_id": "tt4477536",
      "original_language": "en",
      "original_title": "Fifty Shades Freed",
      "overview": "Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.",
      "popularity": 25.757,
      "poster_path": "/9ZedQHPQVveaIYmDSTazhT3y273.jpg",
      "release_date": 2018,
      "revenue": 368307760,
      "runtime": 105,
      "status": "Released",
      "tagline": "Don't Miss the Climax",
      "title": "Fifty Shades Freed",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 4407,
      "trailer": "nJCc5HRPxYA",
      "torrent": "5490A6B04A5CABBA27331114E05871F66EE9780A",
      "es": "https://yify-api.now.sh/subs/tt4477536/44",
      "en": "https://yify-api.now.sh/subs/tt4477536/21",
      "fr": "https://yify-api.now.sh/subs/tt4477536/36",
      "br": "https://yify-api.now.sh/subs/tt4477536/5",
      "ita": "https://yify-api.now.sh/subs/tt4477536/0"
    },
    {
      "adult": false,
      "backdrop_path": "/omoWcwdARBsGHdMdHUk0AQhS2Lp.jpg",
      "budget": 130000000,
      "genres": "Adventure Action Sci-Fi",
      "homepage": "http://www.thehungergames.movie/",
      "id": 101299,
      "imdb_id": "tt1951264",
      "original_language": "en",
      "original_title": "The Hunger Games: Catching Fire",
      "overview": "Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a \"Victor's Tour\" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.",
      "popularity": 29.026,
      "poster_path": "/7c1JtraYsjMMnk8Md0IMoyRzqZJ.jpg",
      "release_date": 2013,
      "revenue": 847423452,
      "runtime": 146,
      "status": "Released",
      "tagline": "Every revolution begins with a spark.",
      "title": "The Hunger Games: Catching Fire",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 12533,
      "trailer": "jyPnQw_Lqds",
      "torrent": "40D0B4BF5A44D73BC7CE64D0D59D2DBDAC424A76",
      "es": "https://yify-api.now.sh/subs/tt1951264/65",
      "en": "https://yify-api.now.sh/subs/tt1951264/13",
      "fr": "https://yify-api.now.sh/subs/tt1951264/37",
      "br": "https://yify-api.now.sh/subs/tt1951264/4",
      "ita": "https://yify-api.now.sh/subs/tt1951264/2"
    },
    {
      "genres": "Crime Thriller Drama",
      "adult": false,
      "backdrop_path": "/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg",
      "belongs_to_collection": null,
      "budget": 55000000,
      "homepage": "http://www.jokermovie.net/",
      "id": 475557,
      "imdb_id": "tt7286456",
      "original_language": "en",
      "original_title": "Joker",
      "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      "popularity": 99.456,
      "poster_path": "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      "release_date": 2019,
      "revenue": 1074151311,
      "runtime": 122,
      "status": "Released",
      "tagline": "Put on a happy face.",
      "title": "Joker",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 12054,
      "trailer": "c5QLnApJX5o",
      "torrent": "2B415A885A3E2210A6EF1D6C57EBA325F20D8BC6",
      "es": "https://yify-api.now.sh/subs/tt7286456/78",
      "en": "https://yify-api.now.sh/subs/tt7286456/27",
      "fr": "https://yify-api.now.sh/subs/tt7286456/56",
      "br": "https://yify-api.now.sh/subs/tt7286456/8",
      "ita": "https://yify-api.now.sh/subs/tt7286456/0"
    },
    {
      "adult": false,
      "backdrop_path": "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
      "budget": 150000000,
      "genres": "Animation Family Adventure",
      "homepage": "https://movies.disney.com/frozen-2",
      "id": 330457,
      "imdb_id": "tt4520988",
      "original_language": "en",
      "original_title": "Frozen II",
      "overview": "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
      "popularity": 69.125,
      "poster_path": "/h6Wi81XNXCjTAcdstiCLRykN3Pa.jpg",
      "release_date": 2019,
      "revenue": 1330764959,
      "runtime": 104,
      "status": "Released",
      "tagline": "The past is not what it seems.",
      "title": "Frozen II",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 4148,
      "trailer": "eSLe4HuKuK0",
      "torrent": "91749F30BCA789524E161FC159931FC4EE554BF0",
      "es": "https://yify-api.now.sh/subs/tt4520988/49",
      "en": "https://yify-api.now.sh/subs/tt4520988/13",
      "fr": "https://yify-api.now.sh/subs/tt4520988/40",
      "br": "https://yify-api.now.sh/subs/tt4520988/3",
      "ita": "https://yify-api.now.sh/subs/tt4520988/0"
    },
    {
      "adult": false,
      "backdrop_path": "/osHKguxvXPIUJJzsO3DEORZZ8QD.jpg",
      "budget": 65000000,
      "genres": "Comedy Drama Romance",
      "homepage": "http://www.sexandthecitymovie.com/",
      "id": 4564,
      "imdb_id": "tt1000774",
      "original_language": "en",
      "original_title": "Sex and the City",
      "overview": "A New York writer on sex and love is finally getting married to her Mr. Big. But her three best girlfriends must console her after one of them inadvertently leads Mr. Big to jilt her.",
      "popularity": 13.642,
      "poster_path": "/nTiuFeutI0TD1CkXNulJlyqq5GL.jpg",
      "release_date": 2008,
      "revenue": 415252786,
      "runtime": 145,
      "status": "Released",
      "tagline": "Get carried away.",
      "title": "Sex and the City",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 1229,
      "trailer": "ZaaLsOyUm_Q",
      "torrent": "6A73985D0E263EEE1AB7AA3652CC6DFA36F9A11E",
      "es": "https://yify-api.now.sh/subs/tt1000774/6",
      "en": "https://yify-api.now.sh/subs/tt1000774/3",
      "fr": "https://yify-api.now.sh/subs/tt1000774/",
      "br": "https://yify-api.now.sh/subs/tt1000774/",
      "ita": "https://yify-api.now.sh/subs/tt1000774/0"
    },
    {
      "adult": false,
      "backdrop_path": "/8iVyhmjzUbvAGppkdCZPiyEHSoF.jpg",
      "belongs_to_collection": null,
      "budget": 63000000,
      "genres": "Drama",
      "homepage": "http://www.foxmovies.com/movies/fight-club",
      "id": 550,
      "imdb_id": "tt0137523",
      "original_language": "en",
      "original_title": "Fight Club",
      "overview": "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
      "popularity": 56.437,
      "poster_path": "/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
      "release_date": 1999,
      "revenue": 100853753,
      "runtime": 139,
      "status": "Released",
      "tagline": "Mischief. Mayhem. Soap.",
      "title": "Fight Club",
      "video": false,
      "vote_average": 8.4,
      "vote_count": 19040,
      "trailer": "BdJKm16Co6M",
      "torrent": "A086CE4AFABBD8AB949662E30134A49E22D1F0C7",
      "es": "https://yify-api.now.sh/subs/tt0137523/68",
      "en": "https://yify-api.now.sh/subs/tt0137523/21",
      "fr": "https://yify-api.now.sh/subs/tt0137523/52",
      "br": "https://yify-api.now.sh/subs/tt0137523/10",
      "ita": "https://yify-api.now.sh/subs/tt0137523/0"
    },
    {
      "adult": false,
      "backdrop_path": "/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
      "belongs_to_collection": null,
      "budget": 175000000,
      "genres": "Animation Family Comedy Adventure Fantasy",
      "homepage": "https://www.pixar.com/feature-films/coco",
      "id": 354912,
      "imdb_id": "tt2380307",
      "original_language": "en",
      "original_title": "Coco",
      "overview": "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
      "popularity": 36.11,
      "poster_path": "/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
      "release_date": 2017,
      "revenue": 800526015,
      "runtime": 105,
      "status": "Released",
      "tagline": "The celebration of a lifetime",
      "title": "Coco",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 11104,
      "trailer": "zNCz4mQzfEI",
      "torrent": "56EA070327C4F34BFB3ADFBEBDA29BB1125799E7",
      "es": "https://yify-api.now.sh/subs/tt2380307/80",
      "en": "https://yify-api.now.sh/subs/tt2380307/18",
      "fr": "https://yify-api.now.sh/subs/tt2380307/59",
      "br": "https://yify-api.now.sh/subs/tt2380307/8",
      "ita": "https://yify-api.now.sh/subs/tt2380307/0"
    },
    {
      "adult": false,
      "backdrop_path": "/skvI4rYFrKXS73BJxWGH54Omlvv.jpg",
      "budget": 85000000,
      "genres": "Fantasy Family Adventure",
      "homepage": "https://movies.disney.com/maleficent-mistress-of-evil",
      "id": 420809,
      "imdb_id": "tt4777008",
      "original_language": "en",
      "original_title": "Maleficent: Mistress of Evil",
      "overview": "Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions by impending nuptials, unexpected allies, and dark new forces at play.",
      "popularity": 44.888,
      "poster_path": "/vloNTScJ3w7jwNwtNGoG8DbTThv.jpg",
      "release_date": 2019,
      "revenue": 491570967,
      "runtime": 118,
      "status": "Released",
      "tagline": "Go beyond the fairy tale",
      "title": "Maleficent: Mistress of Evil",
      "video": false,
      "vote_average": 7.3,
      "vote_count": 2666,
      "trailer": "5MwW1NAsnR8",
      "torrent": "1D70A615E3280EEC79C5576F6C23FECBDA8E24C3",
      "es": "https://yify-api.now.sh/subs/tt4777008/65",
      "en": "https://yify-api.now.sh/subs/tt4777008/12",
      "fr": "https://yify-api.now.sh/subs/tt4777008/43",
      "br": "https://yify-api.now.sh/subs/tt4777008/3",
      "ita": "https://yify-api.now.sh/subs/tt4777008/1"
    },
    {
      "adult": false,
      "backdrop_path": "/yVBQ65YBYZ9UhzJ4NGdRgeXtyTL.jpg",
      "budget": 75000000,
      "genres": "Sci-Fi Adventure Fantasy",
      "homepage": "http://www.thehungergames.movie/",
      "id": 70160,
      "imdb_id": "tt1392170",
      "original_language": "en",
      "original_title": "The Hunger Games",
      "overview": "Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games.  Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains.  Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy.  If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
      "popularity": 19.13,
      "poster_path": "/mgZKtOvxtDX5HtUa5fAVQ5d1Afh.jpg",
      "release_date": 2012,
      "revenue": 691210692,
      "runtime": 142,
      "status": "Released",
      "tagline": "May The Odds Be Ever In Your Favor.",
      "title": "The Hunger Games",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 16214,
      "trailer": "mfmrPu43DF8",
      "torrent": "9C696F27070A6E9927BD165AA77E61108815F8B1",
      "es": "https://yify-api.now.sh/subs/tt1392170/80",
      "en": "https://yify-api.now.sh/subs/tt1392170/19",
      "fr": "https://yify-api.now.sh/subs/tt1392170/54",
      "br": "https://yify-api.now.sh/subs/tt1392170/8",
      "ita": "https://yify-api.now.sh/subs/tt1392170/4"
    },
    {
      "adult": false,
      "backdrop_path": "/16aJtXO6lObbBUr11IvkjB1QD1f.jpg",
      "budget": 55000000,
      "genres": "Drama Romance",
      "homepage": "http://www.fiftyshadesmovie.com/",
      "id": 341174,
      "imdb_id": "tt4465564",
      "original_language": "en",
      "original_title": "Fifty Shades Darker",
      "overview": "When a wounded Christian Grey tries to entice a cautious Ana Steele back into his life, she demands a new arrangement before she will give him another chance. As the two begin to build trust and find stability, shadowy figures from Christian’s past start to circle the couple, determined to destroy their hopes for a future together.",
      "popularity": 15.767,
      "poster_path": "/7CBO9GhsUeMSsWQb47WTPZnKjdj.jpg",
      "release_date": 2017,
      "revenue": 378827494,
      "runtime": 118,
      "status": "Released",
      "tagline": "Every fairy tale has a dark side.",
      "title": "Fifty Shades Darker",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 5140,
      "trailer": "n6BVyk7hty8",
      "torrent": "C6DE831DA45FF4BF4B2067D551BADECA8BFD6B64",
      "es": "https://yify-api.now.sh/subs/tt4465564/76",
      "en": "https://yify-api.now.sh/subs/tt4465564/16",
      "fr": "https://yify-api.now.sh/subs/tt4465564/55",
      "br": "https://yify-api.now.sh/subs/tt4465564/4",
      "ita": "https://yify-api.now.sh/subs/tt4465564/0"
    },
    {
      "adult": false,
      "backdrop_path": "/2DZjKCPnwBKHz5VRX46rKJ9VXnz.jpg",
      "belongs_to_collection": null,
      "budget": 100000000,
      "genres": "Crime Drama Comedy",
      "homepage": "http://www.thewolfofwallstreet.com/",
      "id": 106646,
      "imdb_id": "tt0993846",
      "original_language": "en",
      "original_title": "The Wolf of Wall Street",
      "overview": "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
      "popularity": 34.416,
      "poster_path": "/sOxr33wnRuKazR9ClHek73T8qnK.jpg",
      "release_date": 2013,
      "revenue": 392000694,
      "runtime": 180,
      "status": "Released",
      "tagline": "EARN. SPEND. PARTY.",
      "title": "The Wolf of Wall Street",
      "video": false,
      "vote_average": 8,
      "vote_count": 14969,
      "trailer": "iszwuX1AK6A",
      "torrent": "4B642D022980E5EBAA7CF4B6E1CC93769921CB42",
      "es": "https://yify-api.now.sh/subs/tt0993846/117",
      "en": "https://yify-api.now.sh/subs/tt0993846/21",
      "fr": "https://yify-api.now.sh/subs/tt0993846/82",
      "br": "https://yify-api.now.sh/subs/tt0993846/7",
      "ita": "https://yify-api.now.sh/subs/tt0993846/0"
    },
    {
      "adult": false,
      "backdrop_path": "/oWU6dgu3RgdSZElkhbZuoPtkWAJ.jpg",
      "belongs_to_collection": null,
      "budget": 150000000,
      "genres": "Adventure Comedy Family Animation",
      "homepage": "http://movies.disney.com/moana",
      "id": 277834,
      "imdb_id": "tt3521164",
      "original_language": "en",
      "original_title": "Moana",
      "overview": "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the demigod to set things right.",
      "popularity": 6.808,
      "poster_path": "/n7AJMME1l8xg3S7OKoFasW13N5l.jpg",
      "release_date": 2016,
      "revenue": 695331111,
      "runtime": 107,
      "status": "Released",
      "tagline": "The ocean is calling.",
      "title": "Moana",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 8050,
      "trailer": "pylCYlsjEK0",
      "torrent": "635F4FE104291989E433EF7100C33F6106E85007",
      "es": "https://yify-api.now.sh/subs/tt3521164/79",
      "en": "https://yify-api.now.sh/subs/tt3521164/19",
      "fr": "https://yify-api.now.sh/subs/tt3521164/48",
      "br": "https://yify-api.now.sh/subs/tt3521164/9",
      "ita": "https://yify-api.now.sh/subs/tt3521164/0"
    },
    {
      "adult": false,
      "backdrop_path": "/oJqrhEGdNx1vT665vci9zVgO3Kj.jpg",
      "budget": 11000000,
      "genres": "Comedy Drama Family Music Romance",
      "homepage": "http://disney.go.com/disneypictures/highschoolmusical3",
      "id": 11887,
      "imdb_id": "tt0962726",
      "original_language": "en",
      "original_title": "High School Musical 3: Senior Year",
      "overview": "It's almost graduation day for high school seniors Troy, Gabriella, Sharpay, Chad, Ryan and Taylor ― and the thought of heading off in separate directions after leaving East High has these Wildcats thinking they need to do something they'll remember forever. Together with the rest of the Wildcats, they stage a spring musical reflecting their hopes and fears about the future and their unforgettable experiences growing up together. But with graduation approaching and college plans in question, what will become of the dreams, romances, and friendships of East High's senior Wildcats?",
      "popularity": 19.006,
      "poster_path": "/aq2o1wT0crBOTxof36O6KTyjpgE.jpg",
      "release_date": 2008,
      "revenue": 252909177,
      "runtime": 116,
      "status": "Released",
      "tagline": "",
      "title": "High School Musical 3: Senior Year",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 2502,
      "trailer": "p0FLGx15_W4",
      "torrent": "3B495157C68D1D9F2830F071A8372D2552E6DC54",
      "es": "https://www.seedr.cc/subtitles/1952035514/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-198c0c4c%2Fsid-mgnr6FtgWRV%2CBDM1N-u4myt-qf5%2Ffile%2F1952035514.gz/sub.vtt",
      "en": "",
      "fr": "",
      "br": "",
      "ita": ""
    },
    {
      "adult": false,
      "backdrop_path": "/2l5UHZBcp9cx1PwKLdisJ0gV9jB.jpg",
      "budget": 60000000,
      "genres": "Adventure Animation Comedy Family Fantasy",
      "homepage": "http://www.dreamworksanimation.com/shrek/",
      "id": 808,
      "imdb_id": "tt0126029",
      "original_language": "en",
      "original_title": "Shrek",
      "overview": "It ain't easy bein' green -- especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an unlikely compatriot -- a wisecracking donkey.",
      "popularity": 34.136,
      "poster_path": "/o04jZs5SXhbvhqO4981W7KJXOWZ.jpg",
      "release_date": 2001,
      "revenue": 484409218,
      "runtime": 90,
      "status": "Released",
      "tagline": "The greatest fairy tale never told.",
      "title": "Shrek",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 10394,
      "trailer": "W37DlG1i61s",
      "torrent": "7B973E55B2198EAC530440DC7D9589DD708F5692",
      "es": "https://yify-api.now.sh/subs/tt0126029/33",
      "en": "https://yify-api.now.sh/subs/tt0126029/9",
      "fr": "https://yify-api.now.sh/subs/tt0126029/21",
      "br": "https://yify-api.now.sh/subs/tt0126029/2",
      "ita": "https://yify-api.now.sh/subs/tt0126029/0"
    },
    {
      "adult": false,
      "backdrop_path": "/pfIrxdV1Byf4aWNujP5XwusrWWu.jpg",
      "belongs_to_collection": null,
      "budget": 160000000,
      "genres": "Action Sci-Fi Adventure",
      "homepage": "http://inceptionmovie.warnerbros.com/",
      "id": 27205,
      "imdb_id": "tt1375666",
      "original_language": "en",
      "original_title": "Inception",
      "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      "popularity": 65.265,
      "poster_path": "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      "release_date": 2010,
      "revenue": 825532764,
      "runtime": 148,
      "status": "Released",
      "tagline": "Your mind is the scene of the crime.",
      "title": "Inception",
      "video": false,
      "vote_average": 8.3,
      "vote_count": 25564,
      "trailer": "Jvurpf91omw",
      "torrent": "224BF45881252643DFC2E71ABC7B2660A21C68C4",
      "es": "https://yify-api.now.sh/subs/tt1375666/114",
      "en": "https://yify-api.now.sh/subs/tt1375666/32",
      "fr": "https://yify-api.now.sh/subs/tt1375666/88",
      "br": "https://yify-api.now.sh/subs/tt1375666/15",
      "ita": "https://yify-api.now.sh/subs/tt1375666/0"
    },
    {
      "adult": false,
      "backdrop_path": "/7IGKrY1f1KfwMipx9wZC4NRgIdF.jpg",
      "budget": 40000000,
      "genres": "Drama Romance Thriller",
      "homepage": "https://www.facebook.com/fiftyshadesofgreymovie",
      "id": 216015,
      "imdb_id": "tt2322441",
      "original_language": "en",
      "original_title": "Fifty Shades of Grey",
      "overview": "When college senior Anastasia Steele steps in for her sick roommate to interview prominent businessman Christian Grey for their campus paper, little does she realize the path her life will take. Christian, as enigmatic as he is rich and powerful, finds himself strangely drawn to Ana, and she to him. Though sexually inexperienced, Ana plunges headlong into an affair -- and learns that Christian's true sexual proclivities push the boundaries of pain and pleasure.",
      "popularity": 27.122,
      "poster_path": "/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg",
      "release_date": 2015,
      "revenue": 571006128,
      "runtime": 125,
      "status": "Released",
      "tagline": "Are you curious?",
      "title": "Fifty Shades of Grey",
      "video": false,
      "vote_average": 5.6,
      "vote_count": 7574,
      "trailer": "z4nJX8snP4s",
      "torrent": "4D113D28B14EA6CF66950B645F02FF79EC543E0B",
      "es": "https://yify-api.now.sh/subs/tt2322441/111",
      "en": "https://yify-api.now.sh/subs/tt2322441/26",
      "fr": "https://yify-api.now.sh/subs/tt2322441/69",
      "br": "https://yify-api.now.sh/subs/tt2322441/7",
      "ita": "https://yify-api.now.sh/subs/tt2322441/1"
    },
    {
      "adult": false,
      "backdrop_path": "/txDX7lBx8bBhF7dRCEfDYmAmdnk.jpg",
      "belongs_to_collection": null,
      "budget": 0,
      "genres": "Comedy Romance",
      "homepage": "",
      "id": 200727,
      "imdb_id": "tt1638002",
      "original_language": "en",
      "original_title": "Love, Rosie",
      "overview": "Since the moment they met at age 5, Rosie and Alex have been best friends, facing the highs and lows of growing up side by side. A fleeting shared moment, one missed opportunity, and the decisions that follow send their lives in completely different directions. As each navigates the complexities of life, love, and everything in between, they always find their way back to each other - but is it just friendship, or something more?  Based on Cecelia Ahern's bestselling novel, LOVE, ROSIE is a heart-warming, modern comedy-of-errors posing the ultimate question: do we really only get one shot at true love?",
      "popularity": 16.827,
      "poster_path": "/2HOd431LX9ggqSpBIJ7qyYhATyo.jpg",
      "release_date": 2014,
      "revenue": 4439431,
      "runtime": 102,
      "status": "Released",
      "tagline": "Right Love. Wrong Time.",
      "title": "Love, Rosie",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 4189,
      "trailer": "Cj6i2htlkO4",
      "torrent": "26409EF604E5DC73872DFD609017FE946105F6B1",
      "es": "https://yify-api.now.sh/subs/tt1638002/76",
      "en": "https://yify-api.now.sh/subs/tt1638002/19",
      "fr": "https://yify-api.now.sh/subs/tt1638002/49",
      "br": "https://yify-api.now.sh/subs/tt1638002/6",
      "ita": "https://yify-api.now.sh/subs/tt1638002/0"
    },
    {
      "adult": false,
      "backdrop_path": "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
      "budget": 79000000,
      "genres": "Horror Drama Fantasy",
      "homepage": "http://www.it-movie.net/",
      "id": 474350,
      "imdb_id": "tt7349950",
      "original_language": "en",
      "original_title": "It Chapter Two",
      "overview": "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
      "popularity": 43.362,
      "poster_path": "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
      "release_date": 2019,
      "revenue": 472093228,
      "runtime": 169,
      "status": "Released",
      "tagline": "You'll Float Again",
      "title": "It Chapter Two",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 3884,
      "trailer": "zqUopiAYdRg",
      "torrent": "BC6772B8F0101E515684B91230652DC9434443F2",
      "es": "https://yify-api.now.sh/subs/tt7349950/42",
      "en": "https://yify-api.now.sh/subs/tt7349950/14",
      "fr": "https://yify-api.now.sh/subs/tt7349950/35",
      "br": "https://yify-api.now.sh/subs/tt7349950/4",
      "ita": "https://yify-api.now.sh/subs/tt7349950/0"
    },
    {
      "genres": "Animation, Action, Adventure, Comedy",
      "adult": false,
      "backdrop_path": "/qlYxtqVfu2LOdvYMMDPCSGX0Oz0.jpg",
      "belongs_to_collection": null,
      "budget": 111000000,
      "homepage": "https://family.foxmovies.com/movies/spies-in-disguise",
      "id": 431693,
      "imdb_id": "tt5814534",
      "original_language": "en",
      "original_title": "Spies in Disguise",
      "overview": "Super spy Lance Sterling and scientist Walter Beckett are almost exact opposites. Lance is smooth, suave and debonair. Walter is… not. But what Walter lacks in social skills he makes up for in smarts and invention, creating the awesome gadgets Lance uses on his epic missions. But when events take an unexpected turn, Walter and Lance suddenly have to rely on each other in a whole new way.",
      "popularity": 97.588,
      "poster_path": "/30YacPAcxpNemhhwX0PVUl9pVA3.jpg",
      "release_date": 2019,
      "revenue": 0,
      "runtime": 102,
      "status": "Released",
      "tagline": "Super Spy. Super Fly.",
      "title": "Spies in Disguise",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 962,
      "trailer": "KJv08YJHT8w",
      "torrent": "FC4DDA455EBECB5CADBC0FC8A26D7334EC7FDF7F",
      "es": "https://yify-api.now.sh/subs/tt5814534/23",
      "en": "https://yify-api.now.sh/subs/tt5814534/5",
      "fr": "https://yify-api.now.sh/subs/tt5814534/14",
      "br": "https://yify-api.now.sh/subs/tt5814534/1",
      "ita": "https://yify-api.now.sh/subs/tt5814534/0"
    },
    {
      "genres": "Thriller Action Crime",
      "adult": false,
      "backdrop_path": "/upUy2QhMZEmtypPW3PdieKLAHxh.jpg",
      "budget": 0,
      "homepage": "https://www.badboysforlife.movie/",
      "id": 38700,
      "imdb_id": "tt1502397",
      "original_language": "en",
      "original_title": "Bad Boys for Life",
      "overview": "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
      "popularity": 142.965,
      "poster_path": "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
      "release_date": 2020,
      "revenue": 191150000,
      "runtime": 124,
      "status": "Released",
      "tagline": "Ride together. Die together.",
      "title": "Bad Boys for Life",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 3635,
      "trailer": "1D97elhd5vw",
      "torrent": "B17E2C6CE8D901A59B77F68781500640E5C0D917",
      "es": "https://yify-api.now.sh/subs/tt1502397/86",
      "en": "https://yify-api.now.sh/subs/tt1502397/17",
      "fr": "",
      "br": "https://yify-api.now.sh/subs/tt1502397/8",
      "ita": "https://yify-api.now.sh/subs/tt1502397/0"
    },
    {
      "genres": "Sci-Fi Drama",
      "adult": false,
      "backdrop_path": "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
      "belongs_to_collection": null,
      "budget": 87500000,
      "homepage": "https://www.foxmovies.com/movies/ad-astra",
      "id": 419704,
      "imdb_id": "tt2935510",
      "original_language": "en",
      "original_title": "Ad Astra",
      "overview": "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
      "popularity": 433.51,
      "poster_path": "/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
      "release_date": 2019,
      "revenue": 127175922,
      "runtime": 123,
      "status": "Released",
      "tagline": "The answers we seek are just outside our reach",
      "title": "Ad Astra",
      "video": false,
      "vote_average": 6,
      "vote_count": 3249,
      "trailer": "aBdoxW-R04o",
      "torrent": "79CAD70DCC1BE92E16E890ADD3BB3215F0E6F065",
      "es": "https://yify-api.now.sh/subs/tt2935510/40",
      "en": "https://yify-api.now.sh/subs/tt2935510/10",
      "fr": "https://yify-api.now.sh/subs/tt2935510/24",
      "br": "https://yify-api.now.sh/subs/tt2935510/1",
      "ita": "https://yify-api.now.sh/subs/tt2935510/0"
    },
    {
      "adult": false,
      "backdrop_path": "/2fky2uBBrBpkebvGyGoeApIcZjJ.jpg",
      "budget": 0,
      "genres": "Comedy Drama Family Music Romance",
      "homepage": "http://www.disneychannel.com/highschoolmusical2",
      "id": 13649,
      "imdb_id": "tt0810900",
      "original_language": "en",
      "original_title": "High School Musical 2",
      "overview": "The East High Wildcats are ready to have the time of their lives. Troy is thrilled when he's offered a job in a country club, but it's all part of Sharpay's plot to lure him away from Gabriella. How will it all turn out? All questions are answered on the night of the club's Talent Show.",
      "popularity": 15.428,
      "poster_path": "/la2kiVWDm2vuB4APZDgCCmuBh4K.jpg",
      "release_date": 2007,
      "revenue": 7000000,
      "runtime": 104,
      "status": "Released",
      "tagline": "They're facing their biggest challenge yet.......summer jobs",
      "title": "High School Musical 2",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 2670,
      "trailer": "1sf_v_golDQ",
      "torrent": "50C63F3DC640C4FD6719870BF7E81DA5FF00E19D",
      "es": "https://www.seedr.cc/subtitles/1954219657/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19ba0c5a%2Fsid-be77EuSma5NHuiBvpBli3gB23V9%2Ffile%2F1954219657.gz/sub.vtt",
      "en": "https://yify-api.now.sh/subs/tt0810900/0",
      "fr": "https://yify-api.now.sh/subs/tt0810900/",
      "br": "https://yify-api.now.sh/subs/tt0810900/",
      "ita": "https://yify-api.now.sh/subs/tt0810900/"
    },
    {
      "genres": "Action Adventure Sci-Fi",
      "adult": false,
      "backdrop_path": "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
      "budget": 250000000,
      "homepage": "https://www.starwars.com/films/star-wars-episode-ix-the-rise-of-skywalker",
      "id": 181812,
      "imdb_id": "tt2527338",
      "original_language": "en",
      "original_title": "Star Wars: The Rise of Skywalker",
      "overview": "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
      "popularity": 149.916,
      "poster_path": "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
      "release_date": 2019,
      "revenue": 1073604458,
      "runtime": 142,
      "status": "Released",
      "tagline": "Every generation has a legend",
      "title": "Star Wars: The Rise of Skywalker",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 4298,
      "trailer": "adzYW5DZoWs",
      "torrent": "3D05DB59EEBC36F37F70197B1C527AE0F4DCD0F8",
      "es": "https://yify-api.now.sh/subs/tt2527338/35",
      "en": "https://yify-api.now.sh/subs/tt2527338/12",
      "fr": "https://yify-api.now.sh/subs/tt2527338/21",
      "br": "https://yify-api.now.sh/subs/tt2527338/2",
      "ita": "https://yify-api.now.sh/subs/tt2527338/0"
    },
    {
      "adult": false,
      "backdrop_path": "/rVqY0Bo4Npf6EIONUROxjYAJfmD.jpg",
      "belongs_to_collection": null,
      "budget": 183000000,
      "genres": "Adventure Fantasy Romance Comedy Family",
      "homepage": "https://movies.disney.com/aladdin-2019",
      "id": 420817,
      "imdb_id": "tt6139732",
      "original_language": "en",
      "original_title": "Aladdin",
      "overview": "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
      "popularity": 88.056,
      "poster_path": "/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg",
      "release_date": 2019,
      "revenue": 1047612394,
      "runtime": 128,
      "status": "Released",
      "tagline": "Choose Wisely.",
      "title": "Aladdin",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 5680,
      "trailer": "9g5knnlF7Zo",
      "torrent": "AE57953D3772C804BE36B45FC57198A913014AA1",
      "es": "https://yify-api.now.sh/subs/tt6139732/77",
      "en": "https://yify-api.now.sh/subs/tt6139732/26",
      "fr": "https://yify-api.now.sh/subs/tt6139732/63",
      "br": "https://yify-api.now.sh/subs/tt6139732/8",
      "ita": "https://yify-api.now.sh/subs/tt6139732/0"
    },
    {
      "adult": false,
      "backdrop_path": "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
      "belongs_to_collection": null,
      "budget": 165000000,
      "genres": "Adventure Drama Sci-Fi",
      "homepage": "http://www.interstellarmovie.net/",
      "id": 157336,
      "imdb_id": "tt0816692",
      "original_language": "en",
      "original_title": "Interstellar",
      "overview": "Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      "popularity": 69.259,
      "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      "release_date": 2014,
      "revenue": 675120017,
      "runtime": 169,
      "status": "Released",
      "tagline": "Mankind was born on Earth. It was never meant to die here.",
      "title": "Interstellar",
      "video": false,
      "vote_average": 8.3,
      "vote_count": 22129,
      "trailer": "827FNDpQWrQ",
      "torrent": "89599BF4DC369A3A8ECA26411C5CCF922D78B486",
      "es": "https://yify-api.now.sh/subs/tt0816692/214",
      "en": "https://yify-api.now.sh/subs/tt0816692/42",
      "fr": "https://yify-api.now.sh/subs/tt0816692/160",
      "br": "https://yify-api.now.sh/subs/tt0816692/16",
      "ita": "https://yify-api.now.sh/subs/tt0816692/1"
    },
    {
      "genres": "Action Sci-Fi Comedy Family",
      "adult": false,
      "backdrop_path": "/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
      "belongs_to_collection": null,
      "budget": 85000000,
      "homepage": "https://www.paramountmovies.com/movies/sonic-the-hedgehog",
      "id": 454626,
      "imdb_id": "tt3794354",
      "original_language": "en",
      "original_title": "Sonic the Hedgehog",
      "overview": "Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
      "popularity": 207.89,
      "poster_path": "/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
      "release_date": 2020,
      "revenue": 265493652,
      "runtime": 99,
      "status": "Released",
      "tagline": "A Whole New Speed of Hero",
      "title": "Sonic the Hedgehog",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 3346,
      "trailer": "szby7ZHLnkA",
      "torrent": "F3ACFD3979CC1A30CC7F312673CED688CE78CE77",
      "es": "https://yify-api.now.sh/subs/tt3794354/33",
      "en": "https://yify-api.now.sh/subs/tt3794354/10",
      "fr": "https://yify-api.now.sh/subs/tt3794354/20",
      "br": "https://yify-api.now.sh/subs/tt3794354/3",
      "ita": "https://yify-api.now.sh/subs/tt3794354/1"
    },
    {
      "adult": false,
      "backdrop_path": "/dQ7DzwsIlR0xEiy6AnThS0FIHHo.jpg",
      "budget": 4200000,
      "genres": "Comedy Drama Family Music Romance",
      "homepage": "http://tv.disney.go.com/disneychannel/originalmovies/highschoolmusical/index.html",
      "id": 10947,
      "imdb_id": "tt0475293",
      "original_language": "en",
      "original_title": "High School Musical",
      "overview": "Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school's musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.",
      "popularity": 21.218,
      "poster_path": "/lkcc7eC4qTbhE2DBnoVpGg2ZeM9.jpg",
      "release_date": 2006,
      "revenue": 0,
      "runtime": 98,
      "status": "Released",
      "tagline": "This School Rocks Like No Other!",
      "title": "High School Musical",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 3207,
      "trailer": "ukDLkkvZYFk",
      "torrent": "8FD56D5290A5A23B834265A8C2BBA6FCD2682E02",
      "es": "https://www.seedr.cc/subtitles/1951608030/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19970c4a%2Fsid-7mj95ywwyD8QFNGxhzsMHyqpp6e%2Ffile%2F1951608030.gz/sub.vtt",
      "en": "https://yify-api.now.sh/subs/tt0475293/0",
      "fr": "https://yify-api.now.sh/subs/tt0475293/",
      "br": "https://yify-api.now.sh/subs/tt0475293/",
      "ita": "https://yify-api.now.sh/subs/tt0475293/"
    },
    {
      "adult": false,
      "backdrop_path": "/aOPBIq2kl8RmhowshheqI4M77X7.jpg",
      "belongs_to_collection": null,
      "budget": 85000000,
      "genres": "Animation Family Fantasy Adventure Comedy Romance",
      "homepage": "",
      "id": 11970,
      "imdb_id": "tt0119282",
      "original_language": "en",
      "original_title": "Hercules",
      "overview": "Bestowed with superhuman strength, a young mortal named Hercules sets out to prove himself a hero in the eyes of his father, the great god Zeus. Along with his friends Pegasus, a flying horse, and Phil, a personal trainer, Hercules is tricked by the hilarious, hotheaded villain Hades, who's plotting to take over Mount Olympus!",
      "popularity": 21.005,
      "poster_path": "/tzoKq20x36urYDxS2t3bAM7NsBq.jpg",
      "release_date": 1997,
      "revenue": 252712101,
      "runtime": 93,
      "status": "Released",
      "tagline": "Zero to Hero!",
      "title": "Hercules",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 4627,
      "trailer": "UT5mRId7qUQ",
      "torrent": "4874FAE99578625CD5DE06F9A72B1FBA2FB0A0C9",
      "es": "https://yify-api.now.sh/subs/tt0119282/24",
      "en": "https://yify-api.now.sh/subs/tt0119282/8",
      "fr": "https://yify-api.now.sh/subs/tt0119282/",
      "br": "https://yify-api.now.sh/subs/tt0119282/1",
      "ita": "https://yify-api.now.sh/subs/tt0119282/0"
    },
    {
      "adult": false,
      "backdrop_path": "/4nBAP4CmC4012nJdxUc3pT4jp1.jpg",
      "belongs_to_collection": null,
      "budget": 6500000,
      "genres": "Drama",
      "homepage": "",
      "id": 650,
      "imdb_id": "tt0101507",
      "original_language": "en",
      "original_title": "Boyz n the Hood",
      "overview": "Boyz n the Hood is the popular and successful film and social criticism from John Singleton about the conditions in South Central Los Angeles where teenagers are involved in gun fights and drug dealing on a daily basis.",
      "popularity": 11.297,
      "poster_path": "/7ZreKTSqbLZ0zfJLWyG9QUDbtuY.jpg",
      "release_date": 1991,
      "revenue": 57504069,
      "runtime": 112,
      "status": "Released",
      "tagline": "Once upon a time in South Central L.A... It ain't no fairy tale.",
      "title": "Boyz n the Hood",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 831,
      "trailer": "AE4BdijGtu4",
      "torrent": "F43567E528EA10AF57E5462672CF7B63F7D41594",
      "es": "https://yify-api.now.sh/subs/tt0101507/15",
      "en": "https://yify-api.now.sh/subs/tt0101507/8",
      "fr": "https://yify-api.now.sh/subs/tt0101507/9",
      "br": "https://yify-api.now.sh/subs/tt0101507/1",
      "ita": "https://yify-api.now.sh/subs/tt0101507/0"
    },
    {
      "adult": false,
      "backdrop_path": "/5XlOI0yFHIdAMKJBoN2hMHAZqay.jpg",
      "budget": 20000000,
      "genres": "Drama Action",
      "homepage": "http://www.neverbackdownthemovie.com/",
      "id": 8456,
      "imdb_id": "tt1023111",
      "original_language": "en",
      "original_title": "Never Back Down",
      "overview": "Rebellious Jake Tyler is lured into an ultimate underground fight Scene at his new high school, after receiving threats to the safety of his friends and family Jake decides to seek the mentoring of a veteran fighter who trains him for one final no-holds-barred elimination fight with his nemesis and local martial arts champion Ryan McCarthy.",
      "popularity": 13.904,
      "poster_path": "/4G2FPMqqyh98Vq97VoKBLkhRZ6Z.jpg",
      "release_date": 2008,
      "revenue": 41627431,
      "runtime": 115,
      "status": "Released",
      "tagline": "Win or lose... Everyone has their fight.",
      "title": "Never Back Down",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 1371,
      "trailer": "s8aGqjNM0k4",
      "torrent": "4CD62A0FF658AE7CE5643EBC71A8D1A3FEB5C77F",
      "es": "https://yify-api.now.sh/subs/tt1023111/35",
      "en": "https://yify-api.now.sh/subs/tt1023111/10",
      "fr": "https://yify-api.now.sh/subs/tt1023111/17",
      "br": "https://yify-api.now.sh/subs/tt1023111/3",
      "ita": "https://yify-api.now.sh/subs/tt1023111/0"
    },
    {
      "adult": false,
      "backdrop_path": "/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg",
      "budget": 356000000,
      "genres": "Adventure Sci-Fi Action",
      "homepage": "https://www.marvel.com/movies/avengers-endgame",
      "id": 299534,
      "imdb_id": "tt4154796",
      "original_language": "en",
      "original_title": "Avengers: Endgame",
      "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      "popularity": 51.081,
      "poster_path": "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      "release_date": 2019,
      "revenue": 2797800564,
      "runtime": 181,
      "status": "Released",
      "tagline": "Part of the journey is the end.",
      "title": "Avengers: Endgame",
      "video": false,
      "vote_average": 8.3,
      "vote_count": 12855,
      "trailer": "hA6hldpSTF8",
      "torrent": "414A6F933C48FC7543A9CDB42C854B5457C5BCC7",
      "es": "https://yify-api.now.sh/subs/tt4154796/164",
      "en": "https://yify-api.now.sh/subs/tt4154796/40",
      "fr": "https://yify-api.now.sh/subs/tt4154796/135",
      "br": "https://yify-api.now.sh/subs/tt4154796/17",
      "ita": "https://yify-api.now.sh/subs/tt4154796/0"
    },
    {
      "adult": false,
      "backdrop_path": "/cqegECy0S1NbwtQwlYKcF6GMe87.jpg",
      "belongs_to_collection": null,
      "budget": 10000000,
      "genres": "Drama",
      "homepage": "http://www.miramax.com/movie/good-will-hunting",
      "id": 489,
      "imdb_id": "tt0119217",
      "original_language": "en",
      "original_title": "Good Will Hunting",
      "overview": "Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire.",
      "popularity": 23.684,
      "poster_path": "/ylagLHIbG0F1blqSFqY6pa56Omr.jpg",
      "release_date": 1997,
      "revenue": 225933435,
      "runtime": 127,
      "status": "Released",
      "tagline": "Some people can never believe in themselves, until someone believes in them.",
      "title": "Good Will Hunting",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 7236,
      "trailer": "PaZVjZEFkRs",
      "torrent": "7C0B027DADF7C3B7868D601D3ED5B3CFB3830991",
      "es": "https://yify-api.now.sh/subs/tt0119217/46",
      "en": "https://yify-api.now.sh/subs/tt0119217/15",
      "fr": "https://yify-api.now.sh/subs/tt0119217/31",
      "br": "https://yify-api.now.sh/subs/tt0119217/2",
      "ita": "https://yify-api.now.sh/subs/tt0119217/1"
    },
    {
      "adult": false,
      "backdrop_path": "/xqx5XqTeN3krSM5JFYGsxX81CRk.jpg",
      "belongs_to_collection": null,
      "budget": 14000000,
      "genres": "Comedy War Drama",
      "homepage": "http://www.foxsearchlight.com/jojorabbit",
      "id": 515001,
      "imdb_id": "tt2584384",
      "original_language": "en",
      "original_title": "Jojo Rabbit",
      "overview": "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
      "popularity": 64.939,
      "poster_path": "/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
      "release_date": 2019,
      "revenue": 82468705,
      "runtime": 108,
      "status": "Released",
      "tagline": "An anti-hate satire.",
      "title": "Jojo Rabbit",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 3373,
      "trailer": "VTqd4yNFuSw",
      "torrent": "9764E7C8E879A531EE36DB8BD4748A2734916CB8",
      "es": "https://yify-api.now.sh/subs/tt2584384/23",
      "en": "https://yify-api.now.sh/subs/tt2584384/8",
      "fr": "https://yify-api.now.sh/subs/tt2584384/14",
      "br": "https://yify-api.now.sh/subs/tt2584384/2",
      "ita": "https://yify-api.now.sh/subs/tt2584384/1"
    },
    {
      "genres": "Comedy Thriller Drama",
      "adult": false,
      "backdrop_path": "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      "belongs_to_collection": null,
      "budget": 11363000,
      "homepage": "https://www.parasite-movie.com/",
      "id": 496243,
      "imdb_id": "tt6751668",
      "original_language": "ko",
      "original_title": "기생충",
      "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      "popularity": 169.666,
      "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      "release_date": 2019,
      "revenue": 245924070,
      "runtime": 133,
      "status": "Released",
      "tagline": "Act like you own the place.",
      "title": "Parasite",
      "video": false,
      "vote_average": 8.5,
      "vote_count": 6863,
      "trailer": "isOGD_7hNIY",
      "torrent": "CE6D2A6BBC439A8F6B94B23BA63B04164400FE3B",
      "es": "https://yify-api.now.sh/subs/tt6751668/255",
      "en": "https://yify-api.now.sh/subs/tt6751668/22",
      "fr": "https://yify-api.now.sh/subs/tt6751668/239",
      "br": "https://yify-api.now.sh/subs/tt6751668/10",
      "ita": "https://yify-api.now.sh/subs/tt6751668/0"
    },
    {
      "adult": false,
      "backdrop_path": "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
      "belongs_to_collection": null,
      "budget": 0,
      "genres": "Animation Family Adventure Comedy Fantasy",
      "homepage": "",
      "id": 508439,
      "imdb_id": "tt7146812",
      "original_language": "en",
      "original_title": "Onward",
      "overview": "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
      "popularity": 88.884,
      "poster_path": "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
      "release_date": 2020,
      "revenue": 103181419,
      "runtime": 102,
      "status": "Released",
      "tagline": "Their quest begineth.",
      "title": "Onward",
      "video": false,
      "vote_average": 7.9,
      "vote_count": 1561,
      "trailer": "x8DKg_fsacM",
      "torrent": "9185A249FA36F5743C8315FBAB1B596AF691A3DB",
      "es": "https://yify-api.now.sh/subs/tt7146812/20",
      "en": "https://yify-api.now.sh/subs/tt7146812/8",
      "fr": "",
      "br": "https://yify-api.now.sh/subs/tt7146812/4",
      "ita": "https://yify-api.now.sh/subs/tt7146812/0"
    },
    {
      "adult": false,
      "backdrop_path": "/wKmG0Fuasb9HUD3jgwQamGb5sAq.jpg",
      "belongs_to_collection": null,
      "budget": 28000000,
      "genres": "Drama Music",
      "homepage": "http://www.straightouttacompton.com/",
      "id": 277216,
      "imdb_id": "tt1398426",
      "original_language": "en",
      "original_title": "Straight Outta Compton",
      "overview": "In 1987, five young men, using brutally honest rhymes and hardcore beats, put their frustration and anger about life in the most dangerous place in America into the most powerful weapon they had: their music.  Taking us back to where it all began, Straight Outta Compton tells the true story of how these cultural rebels—armed only with their lyrics, swagger, bravado and raw talent—stood up to the authorities that meant to keep them down and formed the world’s most dangerous group, N.W.A.  And as they spoke the truth that no one had before and exposed life in the hood, their voice ignited a social revolution that is still reverberating today.",
      "popularity": 16.855,
      "poster_path": "/pX1oedva65YAD5P1YdaqbUZz1R3.jpg",
      "release_date": 2015,
      "revenue": 201634991,
      "runtime": 147,
      "status": "Released",
      "tagline": "The Story of N.W.A.",
      "title": "Straight Outta Compton",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 2368,
      "trailer": "OrlLcb7zYmw",
      "torrent": "86B895C4535B1CC6DD9BBD19C5E3430E69E5F609",
      "es": "https://www.seedr.cc/subtitles/1955022885/spa/dl.opensubtitles.org%2Fen%2Fdownload%2Fsrc-api%2Fvrf-19a80c56%2Fsid-JTLKeHsaL2iJDIoqxhRoX-H77Hd%2Ffile%2F1955022885.gz/sub.vtt",
      "en": "https://yify-api.now.sh/subs/tt1398426/",
      "fr": "https://yify-api.now.sh/subs/tt1398426/",
      "br": "https://yify-api.now.sh/subs/tt1398426/",
      "ita": "https://yify-api.now.sh/subs/tt1398426/"
    },
    {
      "genres": "Action Crime Comedy",
      "adult": false,
      "backdrop_path": "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
      "belongs_to_collection": null,
      "budget": 75000000,
      "homepage": "http://www.birdsofpreymovie.net/",
      "id": 495764,
      "imdb_id": "tt7713068",
      "original_language": "en",
      "original_title": "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
      "overview": "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
      "popularity": 154.647,
      "poster_path": "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
      "release_date": 2020,
      "revenue": 201858461,
      "runtime": 109,
      "status": "Released",
      "tagline": "Mind Over Mayhem",
      "title": "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 3477,
      "trailer": "STjEMiKRbQY",
      "torrent": "F49C6932A9D762E36573AE039949E7EC5521E16B",
      "es": "https://yify-api.now.sh/subs/tt7713068/29",
      "en": "https://yify-api.now.sh/subs/tt7713068/11",
      "fr": "https://yify-api.now.sh/subs/tt7713068/25",
      "br": "https://yify-api.now.sh/subs/tt7713068/2",
      "ita": "https://yify-api.now.sh/subs/tt7713068/0"
    },
    {
      "genres": "Comedy Romance",
      "adult": false,
      "backdrop_path": "/6fkqwqLEcDZOEAnBBfKAniwNxtx.jpg",
      "belongs_to_collection": null,
      "budget": 0,
      "homepage": "",
      "id": 475303,
      "imdb_id": "tt7139936",
      "original_language": "en",
      "original_title": "A Rainy Day in New York",
      "overview": "Two young people arrive in New York to spend a weekend, but once they arrive they're met with bad weather and a series of adventures.",
      "popularity": 134.72,
      "poster_path": "/z4A6mFOLTMZAhCSPRyrtzG0SPbd.jpg",
      "release_date": 2019,
      "revenue": 0,
      "runtime": 92,
      "status": "Released",
      "tagline": "Written And Directed By Woody Allen",
      "title": "A Rainy Day in New York",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 884,
      "trailer": "yIVRldiVDL8",
      "torrent": "ACCB9D73FCF8EDF5C084BCD0EA2BBD0EE0223CFB",
      "es": "https://yify-api.now.sh/subs/tt7139936/9",
      "en": "",
      "fr": "https://yify-api.now.sh/subs/tt7139936/7",
      "br": "",
      "ita": "https://yify-api.now.sh/subs/tt7139936/0"
    },
    {
      "genres": 'Action Adventure Sci-Fi',
      "adult": false,
      "backdrop_path": "/5myQbDzw3l8K9yofUXRJ4UTVgam.jpg",
      "budget": 160000000,
      "homepage": "https://www.marvel.com/movies/spider-man-far-from-home",
      "id": 429617,
      "imdb_id": "tt6320628",
      "original_language": "en",
      "original_title": "Spider-Man: Far from Home",
      "overview":
        "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
      "popularity": 86.011,
      "poster_path": "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
      "release_date": 2019,
      "revenue": 1131927996,
      "runtime": 129,
      "status": "Released",
      "tagline": "It’s time to step up.",
      "title": "Spider-Man: Far from Home",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 7047,
      "trailer": "DYYtuKyMtY8",
      "torrent": "37E77490BC4F285DBFA837514715A20BD405A502",
      "es": "https://yify-api.now.sh/subs/tt6320628/73",
      "en": "https://yify-api.now.sh/subs/tt6320628/17",
      "fr": "https://yify-api.now.sh/subs/tt6320628/48",
      "br": "https://yify-api.now.sh/subs/tt6320628/6",
      "ita": "https://yify-api.now.sh/subs/tt6320628/0"
    },
    {
      "genres": "Drama Music",
      "adult": false,
      "backdrop_path": "/93xA62uLd5CwMOAs37eQ7vPc1iV.jpg",
      "belongs_to_collection": null,
      "budget": 52000000,
      "homepage": "http://bohemianrhapsody.com",
      "id": 424694,
      "imdb_id": "tt1727824",
      "original_language": "en",
      "original_title": "Bohemian Rhapsody",
      "overview": "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
      "popularity": 30.236,
      "poster_path": "/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
      "release_date": 2018,
      "revenue": 894027543,
      "runtime": 135,
      "status": "Released",
      "tagline": "Fearless lives forever",
      "title": "Bohemian Rhapsody",
      "video": false,
      "vote_average": 8,
      "vote_count": 10837,
      "trailer": "HlRd9Zy25zo",
      "torrent": "E99CAC0ADD8DECF33B48CCDB96F700209EB675D9",
      "es": "https://yify-api.now.sh/subs/tt1727824/60",
      "en": "https://yify-api.now.sh/subs/tt1727824/17",
      "fr": "https://yify-api.now.sh/subs/tt1727824/41",
      "br": "https://yify-api.now.sh/subs/tt1727824/3",
      "ita": "https://yify-api.now.sh/subs/tt1727824/0"
    },
    {
      "genres": "Adventure Family Animation Action Comedy",
      "adult": false,
      "backdrop_path": "/xTLl2qNYGIEKxqkqKdL5VuR3Er2.jpg",
      "belongs_to_collection": null,
      "budget": 165000000,
      "homepage": "http://movies.disney.com/big-hero-6",
      "id": 177572,
      "imdb_id": "tt2245084",
      "original_language": "en",
      "original_title": "Big Hero 6",
      "overview": "The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.",
      "popularity": 44.279,
      "poster_path": "/xozrGME58olN1xBhtxmjpOoY0jH.jpg",
      "release_date": 2014,
      "revenue": 657818612,
      "runtime": 102,
      "status": "Released",
      "tagline": "",
      "title": "Big Hero 6",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 11544,
      "trailer": "vco0SpSz17g",
      "torrent": "966D30A8BBC61A1FB50842CAB6983B17ECA2CF9A",
      "es": "https://yify-api.now.sh/subs/tt2245084/83",
      "en": "https://yify-api.now.sh/subs/tt2245084/31",
      "fr": "https://yify-api.now.sh/subs/tt2245084/52",
      "br": "https://yify-api.now.sh/subs/tt2245084/12",
      "ita": "https://yify-api.now.sh/subs/tt2245084/0"
    }
  ]
};
